# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Ordinem_iOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ordinem_iOS
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Stripe'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
#  pod 'QRCode'

  target 'Ordinem_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ordinem_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
